#!/bin/sh

set -e

VERSION=$(python3 setup.py --version)
if [ -z "$VERSION" ]; then
   echo "No version found" >&2
   exit 1
fi	
PACKAGE=blaeu
# git commit returns 1 if there is nothing to commit. We use
# diff-index to check that everything is committed
git diff-index --quiet HEAD 
git tag release-${VERSION}
python3 setup.py sdist
gpg --detach-sign -a dist/${PACKAGE}-${VERSION}.tar.gz
twine upload dist/${PACKAGE}-${VERSION}.tar.gz dist/${PACKAGE}-${VERSION}.tar.gz.asc
# Tags are not pushed by 'git push' :-(
git push origin release-${VERSION}
